version: '3.8'

services:
  proxy: 
    container_name: proxy
    image: "nginx:mainline"
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
